id: P009423
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6670
  title: ལབ་སྐྱབས་མགོན་དབང་ཆེན་དགྱེས་རབ་རྡོ་རྗེའི་གསུང་།
  author: ''
  volumes:
    b7e017bad0c14760be463c44792100a6:
      image_group_id: I3CN6672
      title: ''
      volume_number: 1
      total_pages: 193
      base_file: v001.txt
